workflows:
  android-workflow:
    name: Android APK Build
    instance_type: mac_mini_m1
    max_build_duration: 60

    environment:
      flutter: stable

    scripts:
      - name: Flutter bağımlılıklarını yükle
        script: |
          cd flutter_application_1
          flutter pub get

      - name: Android APK oluştur
        script: |
          cd flutter_application_1
          flutter build apk --release

    artifacts:
      - flutter_application_1/build/app/outputs/flutter-apk/app-release.apk
